name: Import podcast episodes from rss feeds

# Allow this workflow to be run manually from the Actions tab
on: workflow_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent import
concurrency:
  group: "import"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Import job
  import:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.import.outputs.result }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f script/requirements.txt ]; then pip install -r script/requirements.txt; fi
    - name: Run the import
      id: import
      run: |
        source script/import.sh
        echo "result=$IMPORT_RESULT" >> $GITHUB_OUTPUT

  deploy:
    needs: import
    if: ${{ needs.import.outputs.result == 'PUSHED' }}
    # Why doesn't this work? 
    # if: ${{ needs.import.steps.import.outputs.result == 'PUSHED' }}
    uses: ./.github/workflows/hugo.yaml
